/// <reference lib="webworker" />
/*
 * SkillSwap service worker — Workbox implementation (InjectManifest).
 *
 * Source of truth: this file. The deployable artifact public/sw.js is
 * GENERATED by scripts/build-sw.mjs (esbuild bundle + precache-manifest
 * injection). Never edit public/sw.js by hand.
 *
 * Routing table (registration order matters — first match wins):
 *
 *   1. Precached URLs (workbox-precaching)  … served from precache
 *   2. API mutations POST/PUT/PATCH/DELETE  … NetworkOnly (never cached,
 *      never fabricated — real network errors reach the app untouched)
 *   3. API GET whitelist                    … NetworkFirst + 5 s timeout
 *                                             → skillswap-api-readonly-v1
 *   4. Fonts (same-origin + gstatic)        … CacheFirst, ~1 year
 *   5. Images (same-origin)                 … CacheFirst, ~30 days
 *   6. Navigations (mode === 'navigate')    … NetworkFirst + 4 s timeout
 *                                             → offline.html fallback
 *   7. Everything else                      … NOT intercepted; plain network
 *
 * NOTE: `navigator.onLine` is never consulted here. It reports interface
 * state, not reachability — strategies react to real request outcomes.
 */

import { clientsClaim, setCacheNameDetails } from 'workbox-core';
import {
  cleanupOutdatedCaches,
  matchPrecache,
  precacheAndRoute,
} from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import {
  CacheFirst,
  NetworkFirst,
  NetworkOnly,
} from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import * as navigationPreload from 'workbox-navigation-preload';

declare const self: ServiceWorkerGlobalScope;

/**
 * Inlined at build time by scripts/build-sw.mjs from NEXT_PUBLIC_API_URL.
 * e.g. "https://skillswap-nest-backend-app.onrender.com/api" (no trailing slash).
 */
declare const __API_BASE__: string;

// ---------------------------------------------------------------------------
// Cache naming (§7) — project-specific, easy to find in DevTools.
// Bump VERSION when a runtime cache's schema/contents change meaningfully;
// Workbox handles precache revisioning on its own (§24).
// ---------------------------------------------------------------------------
const VERSION = 'v1';
const PAGES_CACHE = `skillswap-runtime-pages-${VERSION}`;
const IMAGES_CACHE = `skillswap-runtime-images-${VERSION}`;
const FONTS_CACHE = `skillswap-runtime-fonts-${VERSION}`;
const API_CACHE = `skillswap-api-readonly-${VERSION}`;
const OFFLINE_URL = '/offline.html';

setCacheNameDetails({ prefix: 'skillswap' }); // precache: skillswap-precache-v2-…

precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches(); // removes old workbox-precache-* versions

// ---------------------------------------------------------------------------
// API helpers
// ---------------------------------------------------------------------------
let API_ORIGIN = '';
let API_PATH_PREFIX = '';
try {
  const parsed = new URL(__API_BASE__);
  API_ORIGIN = parsed.origin;
  // "/api" when the base is https://host/api — "" for a bare host.
  API_PATH_PREFIX = parsed.pathname.replace(/\/+$/, '');
} catch {
  /* invalid config → all API routes stay disabled, requests pass through */
}

function isApiUrl(url: URL): boolean {
  if (API_ORIGIN && url.origin === API_ORIGIN) {
    return url.pathname.startsWith(API_PATH_PREFIX || '/');
  }
  // Also cover a same-origin /api proxy setup.
  return url.origin === self.location.origin && url.pathname.startsWith('/api/');
}

/** Path relative to the API prefix, e.g. "/tasks/12/applications". */
function apiPath(url: URL): string {
  if (url.origin === API_ORIGIN && API_PATH_PREFIX) {
    return url.pathname.slice(API_PATH_PREFIX.length) || '/';
  }
  return url.pathname.replace(/^\/api/, '') || '/';
}

/**
 * Explicit READ-ONLY cache allowlist (§10). Deliberately EXCLUDED:
 *   /auth/*    — authentication responses are never cached
 *   /users/me  — authorization-sensitive personal data (the app already
 *                keeps the last profile in localStorage for cold boots)
 *   anything else not listed — falls through to the network untouched
 *
 * Included: marketplace task content and the user's own point history /
 * balance (readonly financial data, per §26: NetworkFirst only, short TTL —
 * the UI labels it as last-synced whenever the offline banner is visible).
 */
const CACHEABLE_API_GET = new RegExp(
  '^/(?:' +
    'tasks(?:/\\d+(?:/applications)?)?' +
    '|transactions(?:/(?:me|balance))?' +
    ')/?$',
);

// ---------------------------------------------------------------------------
// 2. API mutations — NetworkOnly (§11). Registered FIRST so they always win.
//    A failed mutation surfaces as a genuine network error to the page;
//    the service worker never fabricates a 503 response body.
// ---------------------------------------------------------------------------
if (API_ORIGIN) {
  const mutationHandler = new NetworkOnly();
  for (const method of ['POST', 'PUT', 'PATCH', 'DELETE'] as const) {
    registerRoute(({ url }) => isApiUrl(url), mutationHandler, method);
  }

  // 3. Whitelisted API GETs — NetworkFirst, only HTTP 200 cached, 10 min TTL.
  registerRoute(
    ({ url }) => isApiUrl(url) && CACHEABLE_API_GET.test(apiPath(url)),
    new NetworkFirst({
      cacheName: API_CACHE,
      networkTimeoutSeconds: 5,
      plugins: [
        new CacheableResponsePlugin({ statuses: [200] }),
        new ExpirationPlugin({
          maxEntries: 60,
          maxAgeSeconds: 10 * 60,
          purgeOnQuotaError: true,
        }),
      ],
    }),
    'GET',
  );
}

// ---------------------------------------------------------------------------
// 4. Fonts — immutable in practice; long-lived cache (§17).
//    Inter is self-hosted by next/font under /_next/static/media;
//    fonts.gstatic.com covered defensively. Status 0 allowed for opaque
//    cross-origin responses.
// ---------------------------------------------------------------------------
registerRoute(
  ({ url, request }) =>
    request.method === 'GET' &&
    ((url.origin === self.location.origin ||
      url.origin === 'https://fonts.gstatic.com') &&
      /\.(?:woff2?|ttf|otf)$/i.test(url.pathname)),
  new CacheFirst({
    cacheName: FONTS_CACHE,
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60,
        purgeOnQuotaError: true,
      }),
    ],
  }),
);
// ---------------------------------------------------------------------------
// 5. Same-origin images (incl. /_next/image optimizer output) — CacheFirst
//    with bounded entries and TTL (§16). Remote hosts are intentionally not
//    cached: the app currently ships no third-party image CDN assets.
// ---------------------------------------------------------------------------
registerRoute(
  ({ url, request }) =>
    url.origin === self.location.origin &&
    request.method === 'GET' &&
    (/\.(?:png|jpe?g|gif|webp|avif|ico|svg)$/i.test(url.pathname) ||
      url.pathname.startsWith('/_next/image')),
  new CacheFirst({
    cacheName: IMAGES_CACHE,
    plugins: [
      new CacheableResponsePlugin({ statuses: [200] }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60,
        purgeOnQuotaError: true,
      }),
    ],
  }),
);

// ---------------------------------------------------------------------------
// 6. Navigations — NetworkFirst with navigation preload (§20): the browser
//    starts the document request while the SW boots; workbox-strategies'
//    StrategyHandler consumes event.preloadResponse automatically.
//    On failure: previously cached page → precached /offline.html.
//    This handler can NEVER answer API requests (mode === 'navigate' only),
//    so there is no global offline-JSON trap (§18).
// ---------------------------------------------------------------------------
navigationPreload.enable();

const pagesStrategy = new NetworkFirst({
  cacheName: PAGES_CACHE,
  networkTimeoutSeconds: 4,
  plugins: [
    new CacheableResponsePlugin({ statuses: [200] }),
    new ExpirationPlugin({
      maxEntries: 30,
      maxAgeSeconds: 7 * 24 * 60 * 60,
      purgeOnQuotaError: true,
    }),
  ],
});

async function handleNavigation(options: {
  event: ExtendableEvent;
  request: Request;
}): Promise<Response> {
  // The router always dispatches navigations with the real FetchEvent
  // (which carries preloadResponse); extend onward to keep strategy typing.
  const event = options.event as FetchEvent;
  const request = options.request;
  let response: Response | undefined;
  try {
    response = await pagesStrategy.handle({ event, request });
  } catch {
    /* fall through to the offline fallback */
  }
  if (response) return response;

  try {
    const fallback = await matchPrecache(OFFLINE_URL);
    if (fallback) return fallback;
  } catch {
    /* precache unavailable — propagate a network error below */
  }
  return Response.error();
}

registerRoute(({ request }) => request.mode === 'navigate', handleNavigation);

// ---------------------------------------------------------------------------
// Lifecycle & controlled updates (§21)
// ---------------------------------------------------------------------------
// Legacy vanilla-SW caches from previous deployments — removed once, then gone.
const LEGACY_CACHE_RE = /^skillswap-(shell|assets|api)-v\d+$/;

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((key) => LEGACY_CACHE_RE.test(key))
          .map((key) => caches.delete(key)),
      );
      console.log(`[SW] active (${VERSION})`);
    })(),
  );
});

// Take control of open tabs once an update has been approved by the page.
clientsClaim();

// The page decides WHEN a waiting worker activates — never automatically
// (no unconditional skipWaiting: avoids old-HTML/new-JS hydration mismatches).
self.addEventListener('message', (event) => {
  if ((event.data as { type?: string } | undefined)?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

